CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  foto_perfil TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);